apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: My-django-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: My-django-app
    app.kubernetes.io/instance: My-django-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nireekshith-r/Test-Repo
    targetRevision: main
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: My-django-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my-slack-channel
    notifications.argoproj.io/subscribe.on-sync-failed.slack: my-slack-channel