apiVersion: v1
kind: Secret
metadata:
  name: my-django-app-secret
  namespace: my-django-app
type: Opaque
stringData:
  # Replace with actual sensitive values
  example-secret-key: example-secret-value