apiVersion: v1
kind: Service
metadata:
  name: my-django-app
  namespace: my-django-app
  labels:
    app: my-django-app
spec:
  type: ClusterIP
  selector:
    app: my-django-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000